### ISSUE TITLE
Verify the actual stored size on disk

### ISSUE THREAD

**Issue by AuHau** [rsksmart/rif-storage-pinner#124]
Currently, we are "blindly" trusting the `ipfs object stat` to provide us the correct size. This is fine for the check before actual pinning, but we should verify after pinning (eq. fetching the data to the local node) that the size more or less matches the original size.

This won't be trivial though. There is no support for this from IPFS and hence we will have to devise a mechanism to read the actual IPFS repo's block store. Problem is that the store uses sharding and other encoding mechanisms, so we have to reverse-engineer this to decode where each block is placed and then sum the sizes.

An alternative is to use the datastore abstraction packages like https://github.com/ipfs/js-datastore-fs but from API perspective it seems that there is no "get size" call and hence we would actually have to load all the information into memory to just get a size. In anyway these packages can show us what mechanisms they use.

**Comment by AuHau** [comment]
The upcoming feature of `go-ipfs` `ipfs dag stat` will solve this for us as it calculates the size directly based on the data.

**Comment by AuHau** [comment]
This is blocked by supporting the `dag stat` command in `js-ipfs`: https://github.com/ipfs/js-ipfs/issues/3283

**Comment by julianmrodri** [comment]
@AuHau should we close this now that was implemented?

**Comment by AuHau** [comment]
I guess we can.
