### ISSUE TITLE
Room topic is not contract bounded

### ISSUE THREAD

**Issue by AuHau** [rsksmart/rif-storage-pinner#239]
As per [Comms spec](https://hackmd.io/fA2Q3N9qSW6ZGCV3rlIHcw?view#Room%E2%80%99s-topics) the Room topic should be generated as:
```
<evm_network_id>:<contract_address>:<offer_id>
```

Currently, we do not incorporate the contract address into it. Not sure why. I believe it was my shortcoming and wanted to return to it and forgot about it. This will have to be fixed in Cache and the Upload Service as well.

**Comment by julianmrodri** [comment]
Hi this was done right?

**Comment by nduchak** [comment]
Yes, I link a related PR
