### ISSUE TITLE
Extend CLI

### ISSUE THREAD

**Issue by AuHau** [rsksmart/rif-storage-pinner#91]
Since the functionality is growing, we might want to switch from simple "single-commmand" CLI style into "multi-command" CLI to have better separation of functionalities.

Proposal on the layout:

 - `daemon` - long running task that does the actual pinning/unpinning, listening on events etc
 - `jobs` - lists the current pinning jobs as per #78
 - `cleanup` - task which can do things like remove the local database, unpin all the current Agreements etc

Any other suggestion?

**Comment by nduchak** [comment]
`Agreements` command table column:
 - reference
 - hash
 - status(if error, show message, number of retries)
 - expiration date
